#!/bin/bash

#CUDA_VISIBLE_DEVICES=2 python train.py  -mode nmt_char -epochs 100 -batch_size 16 -lr 0.00001 -grad_clip 1.0 -path '../../../data/AI_chanllenger2017/data_1000k_char_new/' -extension '.zh .en'  -train 'train' -valid 'val' -test 'test' -embed_size 256 -hidden_size 512 -nmt_encoder_layers 2 -nmt_decoder_layers 1 -ctc_layers 2 -dropout 0.3 -nmt_result_file 'checkpoints/test_nmt_result_exp1.txt' -val_nmt_result_file 'checkpoints/val_nmt_result_exp1.txt'  -save_path 'checkpoints/charWord_zhen_exp1' -log_FileName 'checkpoints/log_exp1'  -model_cell 'LSTM' --tgt_dict_maxSize 50000

#CUDA_VISIBLE_DEVICES=2 python train.py  -mode nmt_char -epochs 100 -batch_size 8 -lr 0.00001 -grad_clip 1.0 -path '../../../data/AI_chanllenger2017/data_1000k_char_new/' -extension '.zh .en'  -train 'train' -valid 'val' -test 'test' -embed_size 256 -hidden_size 512 -nmt_encoder_layers 2 -nmt_decoder_layers 1 -ctc_layers 2 -dropout 0.3 -nmt_result_file 'checkpoints/test_nmt_result_exp2.txt' -val_nmt_result_file 'checkpoints/val_nmt_result_exp2.txt' -save_path 'checkpoints/charWord_zhen_exp2' -log_FileName 'checkpoints/log_exp2'  -model_cell 'GRU' -tgt_dict_maxSize 50000

#CUDA_VISIBLE_DEVICES=2 python train.py  -mode nmt_char -epochs 100 -batch_size 16 -lr 0.00001 -grad_clip 1.0 -path '../../../data/AI_chanllenger2017/data_1000k_char_new/' -extension '.zh .en'  -train 'train' -valid 'val' -test 'test' -embed_size 256 -hidden_size 512 -nmt_encoder_layers 2 -nmt_decoder_layers 2 -ctc_layers 2 -dropout 0.3 -nmt_result_file 'checkpoints/test_nmt_result_exp3.txt' -val_nmt_result_file 'checkpoints/val_nmt_result_exp3.txt'  -save_path 'checkpoints/charWord_zhen_exp3' -log_FileName 'checkpoints/log_exp3'  -model_cell 'LSTM' -tgt_dict_maxSize 50000

#CUDA_VISIBLE_DEVICES=3 python train.py  -mode nmt_char -epochs 100 -batch_size 8 -lr 0.00001 -grad_clip 1.0 -path '../../../data/AI_chanllenger2017/data_1000k_char_new/' -extension '.zh .en'  -train 'train' -valid 'val' -test 'test' -embed_size 256 -hidden_size 512 -nmt_encoder_layers 2 -nmt_decoder_layers 2 -ctc_layers 2 -dropout 0.3 -nmt_result_file 'checkpoints/test_nmt_result_exp4.txt' -val_nmt_result_file 'checkpoints/val_nmt_result_exp4.txt' -save_path 'checkpoints/charWord_zhen_exp4' -log_FileName 'checkpoints/log_exp4'  -model_cell 'GRU' -tgt_dict_maxSize 50000

#CUDA_VISIBLE_DEVICES=2 python train.py  -mode nmt_char -epochs 100 -batch_size 8 -lr 0.0001 -grad_clip 1.0 -path '../../../data/AI_chanllenger2017/data_1000k_char_new/' -extension '.zh .en'  -train 'train' -valid 'val' -test 'test' -embed_size 256 -hidden_size 512 -nmt_encoder_layers 2 -nmt_decoder_layers 1 -ctc_layers 2 -dropout 0.3 -nmt_result_file 'checkpoints/test_nmt_result_exp5.txt' -val_nmt_result_file 'checkpoints/val_nmt_result_exp5.txt' -save_path 'checkpoints/charWord_zhen_exp5' -log_FileName 'checkpoints/log_exp5'  -model_cell 'LSTM' -tgt_dict_maxSize 50000

#CUDA_VISIBLE_DEVICES=2 python train.py  -mode nmt_char -epochs 100 -batch_size 8 -lr 0.0001 -grad_clip 1.0 -path '../../../data/AI_chanllenger2017/data_1000k_char_new/' -extension '.zh .en'  -train 'train' -valid 'val' -test 'test' -embed_size 256 -hidden_size 512 -nmt_encoder_layers 2 -nmt_decoder_layers 1 -ctc_layers 2 -dropout 0.3 -nmt_result_file 'checkpoints/test_nmt_result_exp6.txt' -val_nmt_result_file 'checkpoints/val_nmt_result_exp6.txt' -save_path 'checkpoints/charWord_zhen_exp6' -log_FileName 'checkpoints/log_exp6'  -model_cell 'GRU' -tgt_dict_maxSize 50000

#CUDA_VISIBLE_DEVICES=2 python train.py  -mode nmt_char -epochs 100 -batch_size 8 -lr 0.00005 -grad_clip 1.0 -path '../../../data/AI_chanllenger2017/data_1000k_char_new/' -extension '.zh .en'  -train 'train' -valid 'val' -test 'test' -embed_size 256 -hidden_size 512 -nmt_encoder_layers 2 -nmt_decoder_layers 1 -ctc_layers 2 -dropout 0.3 -nmt_result_file 'checkpoints/test_nmt_result_exp7.txt' -val_nmt_result_file 'checkpoints/val_nmt_result_exp7.txt' -save_path 'checkpoints/charWord_zhen_exp7' -log_FileName 'checkpoints/log_exp7'  -model_cell 'LSTM' -tgt_dict_maxSize 50000

#CUDA_VISIBLE_DEVICES=2 python train.py  -mode nmt_char -epochs 100 -batch_size 8 -lr 0.00005 -grad_clip 1.0 -path '../../../data/AI_chanllenger2017/data_1000k_char_new/' -extension '.zh .en'  -train 'train' -valid 'val' -test 'test' -embed_size 256 -hidden_size 512 -nmt_encoder_layers 2 -nmt_decoder_layers 1 -ctc_layers 2 -dropout 0.3 -nmt_result_file 'checkpoints/test_nmt_result_exp8.txt' -val_nmt_result_file 'checkpoints/val_nmt_result_exp8.txt' -save_path 'checkpoints/charWord_zhen_exp8' -log_FileName 'checkpoints/log_exp8'  -model_cell 'GRU' -tgt_dict_maxSize 50000

#CUDA_VISIBLE_DEVICES=2 python train.py  -mode nmt_char -epochs 100 -batch_size 8 -lr 0.0001 -grad_clip 1.0 -path '../../../data/AI_chanllenger2017/data_1000k_char_new/' -extension '.zh .en'  -train 'train' -valid 'val' -test 'test' -embed_size 256 -hidden_size 512 -nmt_encoder_layers 2 -nmt_decoder_layers 2 -ctc_layers 2 -dropout 0.3 -nmt_result_file 'checkpoints/test_nmt_result_exp9.txt' -val_nmt_result_file 'checkpoints/val_nmt_result_exp9.txt' -save_path 'checkpoints/charWord_zhen_exp9' -log_FileName 'checkpoints/log_exp9'  -model_cell 'LSTM' -tgt_dict_maxSize 50000

#CUDA_VISIBLE_DEVICES=3 python train.py  -mode nmt_char -epochs 100 -batch_size 8 -lr 0.0001 -grad_clip 1.0 -path '../../../data/AI_chanllenger2017/data_1000k_char_new/' -extension '.zh .en'  -train 'train' -valid 'val' -test 'test' -embed_size 256 -hidden_size 512 -nmt_encoder_layers 2 -nmt_decoder_layers 2 -ctc_layers 2 -dropout 0.3 -nmt_result_file 'checkpoints/test_nmt_result_exp10.txt' -val_nmt_result_file 'checkpoints/val_nmt_result_exp10.txt' -save_path 'checkpoints/charWord_zhen_exp10' -log_FileName 'checkpoints/log_exp10'  -model_cell 'GRU' -tgt_dict_maxSize 50000


#un data
#CUDA_VISIBLE_DEVICES=2 python train.py  -mode nmt_char -epochs 100 -batch_size 8 -lr 0.00001 -grad_clip 1.0 -path '../../../data/Multi_UN/un_data/' -extension '.maxl50_100.zh .maxl50_100.en'  -train 'train' -valid 'val' -test 'test' -embed_size 256 -hidden_size 512 -nmt_encoder_layers 2 -nmt_decoder_layers 1 -ctc_layers 2 -dropout 0.3 -nmt_result_file 'checkpoints/un_test_nmt_result_exp1.txt' -val_nmt_result_file 'checkpoints/un_val_nmt_result_exp1.txt'  -save_path 'checkpoints/un_charWord_zhen_exp1' -log_FileName 'checkpoints/un_log_exp1'  -model_cell 'LSTM' -tgt_dict_maxSize 50000

CUDA_VISIBLE_DEVICES=3 python train.py  -mode nmt_char -epochs 100 -batch_size 8 -lr 0.00001 -grad_clip 1.0 -path '../../../data/Multi_UN/un_data/' -extension '.maxl50_100.zh .maxl50_100.en'  -train 'train' -valid 'val' -test 'test' -embed_size 256 -hidden_size 512 -nmt_encoder_layers 2 -nmt_decoder_layers 1 -ctc_layers 2 -dropout 0.3 -nmt_result_file 'checkpoints/un_test_nmt_result_exp2.txt' -val_nmt_result_file 'checkpoints/un_val_nmt_result_exp2.txt' -save_path 'checkpoints/un_charWord_zhen_exp2' -log_FileName 'checkpoints/un_log_exp2'  -model_cell 'GRU' -src_dict_maxSize 5000 -tgt_dict_maxSize 50000

#CUDA_VISIBLE_DEVICES=1 python train.py  -mode nmt_char -epochs 100 -batch_size 8 -lr 0.00001 -grad_clip 1.0 -path '../../../data/Multi_UN/un_data/' -extension '.maxl50.zh .maxl50.en'  -train 'train' -valid 'val' -test 'test' -embed_size 256 -hidden_size 512 -nmt_encoder_layers 2 -nmt_decoder_layers 1 -ctc_layers 2 -dropout 0.3 -nmt_result_file 'checkpoints/un_test_nmt_result_exp2.txt' -val_nmt_result_file 'checkpoints/un_val_nmt_result_exp2.txt' -save_path 'checkpoints/un_charWord_zhen_exp2' -log_FileName 'checkpoints/temp'  -model_cell 'GRU' -src_dict_maxSize 10000 -tgt_dict_maxSize 50000




#CUDA_VISIBLE_DEVICES=1 python train.py  -mode update_twoLoss -epochs 100 -batch_size 8 -lr 0.00001 -grad_clip 1.0 -path '../../../data/nmt_seg_TiZh/' -extension '.ti .zh .seg'  -train 'train' -valid 'valid' -test 'test-2017' -embed_size 256 -hidden_size 512 -nmt_encoder_layers 2 -nmt_decoder_layers 1 -ctc_layers 2 -dropout 0.3 -nmt_result_file 'checkpoints/test_temp.txt' -val_nmt_result_file 'checkpoints/val_nmt_temp.txt' -save_path 'checkpoints/temp' -log_FileName 'checkpoints/log_temp'  -model_cell 'GRU' -src_dict_maxSize 50000 -seg_dict_maxSize 50000 -tgt_dict_maxSize 50000

#CUDA_VISIBLE_DEVICES=1 python train.py  -mode combine -epochs 100 -batch_size 8 -lr 0.00001 -grad_clip 1.0 -path '../../../data/AI_chanllenger2017/data_1000k_char/' -extension '.zh .en .seg'  -train 'train' -valid 'val' -test 'test' -embed_size 256 -hidden_size 512 -nmt_encoder_layers 2 -nmt_decoder_layers 1 -ctc_layers 2 -dropout 0.3 -nmt_result_file 'checkpoints/test_temp.txt' -val_nmt_result_file 'checkpoints/val_nmt_temp.txt' -save_path 'checkpoints/temp' -log_FileName 'checkpoints/log_temp'  -model_cell 'LSTM' -src_dict_maxSize 50000 -seg_dict_maxSize 50000 -tgt_dict_maxSize 50000


#CUDA_VISIBLE_DEVICES=0 python train.py  -mode ctc  -epochs 100 -batch_size 16 -lr 0.00001 -grad_clip 1.0 -path '../../../data/AI_chanllenger2017/data_1000k_char/' -extension '.zh .seg'  -train 'train' -valid 'val' -test 'test' -embed_size 256 -hidden_size 512 -nmt_encoder_layers 2 -nmt_decoder_layers 1 -ctc_layers 2 -dropout 0.3 -nmt_result_file 'checkpoints/test_nmt_result.txt' -save_path 'checkpoints/test' -log_FileName 'checkpoints/log_test'  -model_cell 'GRU'

#CUDA_VISIBLE_DEVICES='0' python train.py -mode update_twoLoss -epochs 100 -batch_size 12 -lr 0.00001 -grad_clip 10.0 -path '/vision_data/wanglihui/AI_chanllenger2017/data_1000k_char/' -extension '.zh .en .seg' -train 'train' -valid 'val' -test 'test' -nmt_result_file 'test_nmt_result.txt' -seg_result_file 'test_ctc_result.txt' -init_CTC_model 'init_CTCModel/init_ctcModel_6.pt'
